set history=500
set hlsearch                       " Highlight search results
set ignorecase smartcase           " Search queries intelligently set case
set incsearch                      " Show search results as you type
set number                         " Enable line numbers
set scrolloff=5                    " Leave 5 lines of buffer when scrolling
set shiftwidth=2 tabstop=2  	   " Two spaces for tabs everywhere
set showcmd                        " Show size of visual selection
set sidescrolloff=10               " Leave 10 characters of horizontal buffer when scrolling
set timeoutlen=1000 ttimeoutlen=0  " Remove timeout when hitting escape
